name: Autoapprove PRs that contain only commits that exist in a trusted branch.

inputs:
    trusted-branches:
        description: A list of trusted branches
        default: 'master; main'
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3.4.0
          with:
              ref: ${{ github.head_ref }}
              fetch-depth: 0
        - name: Check if only contains commits in a trusted branch.
          run: |
              IFS=';' read -r -a branches <<< "${{ inputs.trusted-branches }}"
              for b in "${branches[@]}"; do
                  b=$(echo $b | xargs) # trims whitespace
                  if git merge-base --is-ancestor origin/${{ github.head_ref }} origin/$b; then
                      echo -e "\033[32m${{ github.head_ref }} only contains commits found in $b"
                      exit 0;
                  fi
              done
              echo -e "\033[31m${{ github.head_ref }} contains commits not found in any trusted branch (${{ inputs.trusted-branches }})"
              exit 1;
          shell: bash
        - uses: hmarr/auto-approve-action@v3.2.1
