name: Autoapprove PRs that contain only commits that exist in a trusted branch.

inputs:
    trusted-branch:
        description: A list of trusted branches
        default: main
        required: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
          with:
              ref: ${{ inputs.trusted-branch }}
              fetch-depth: 0
        - name: Check if only contains commits in a trusted branch.
          run: |
              if git merge-base --is-ancestor origin/${{ github.head_ref }} origin/${{ inputs.trusted-branch }}; then
                  echo -e "\033[32m${{ github.head_ref }} only contains commits found in QA"
              else
                  echo -e "\033[31m${{ github.head_ref }} contains commits not found in QA"
                  exit 1;
              fi
          shell: bash
        - uses: hmarr/auto-approve-action@v3
